# Generated by Django 5.2 on 2025-04-08 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_meal', models.CharField(max_length=255)),
                ('morning_quantity', models.PositiveIntegerField()),
                ('evening_meal', models.CharField(max_length=255)),
                ('evening_quantity', models.PositiveIntegerField()),
                ('dinner_meal', models.CharField(max_length=255)),
                ('dinner_quantity', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
